services:
  statefull-go-app:
    build: .
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb: